// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Devices.Registration.Clients.Devices.V20190115.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for OperationStatusLookup operation.
    /// </summary>
    public partial class RuntimeRegistrationOperationStatusLookupHeaders
    {
        /// <summary>
        /// Initializes a new instance of the
        /// RuntimeRegistrationOperationStatusLookupHeaders class.
        /// </summary>
        public RuntimeRegistrationOperationStatusLookupHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// RuntimeRegistrationOperationStatusLookupHeaders class.
        /// </summary>
        /// <param name="retryAfter">The retry interval in seconds.</param>
        /// <param name="location">The location of the resource.</param>
        public RuntimeRegistrationOperationStatusLookupHeaders(string retryAfter = default(string), string location = default(string))
        {
            RetryAfter = retryAfter;
            Location = location;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the retry interval in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "Retry-After")]
        public string RetryAfter { get; set; }

        /// <summary>
        /// Gets or sets the location of the resource.
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

    }
}
