// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Devices.Registration.Clients.Devices.V20190115.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Registration result returned when using SymmetricKey attestation
    /// </summary>
    public partial class SymmetricKeyRegistrationResult
    {
        /// <summary>
        /// Initializes a new instance of the SymmetricKeyRegistrationResult
        /// class.
        /// </summary>
        public SymmetricKeyRegistrationResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SymmetricKeyRegistrationResult
        /// class.
        /// </summary>
        public SymmetricKeyRegistrationResult(string enrollmentGroupId = default(string))
        {
            EnrollmentGroupId = enrollmentGroupId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enrollmentGroupId")]
        public string EnrollmentGroupId { get; set; }

    }
}
