// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Devices.Registration.Clients.Devices.V20190115.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// TPM registration result.
    /// </summary>
    public partial class TpmRegistrationResult
    {
        /// <summary>
        /// Initializes a new instance of the TpmRegistrationResult class.
        /// </summary>
        public TpmRegistrationResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TpmRegistrationResult class.
        /// </summary>
        public TpmRegistrationResult(string authenticationKey = default(string))
        {
            AuthenticationKey = authenticationKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authenticationKey")]
        public string AuthenticationKey { get; set; }

    }
}
